create database payroll_services;
show databases;
use payroll_services;
create table employee_payroll(id int not null auto_increment primary key,empName varchar(25),salary double,startDate date);
desc employee_payroll;
insert into employee_payroll(empname,salary,startDate) values('jaya',1200,'2021-11-30');
insert into employee_payroll(empname,salary,startDate) values('parvati',12000,'2020-9-21');
insert into employee_payroll(empname,salary,startDate) values('priyanka',5263,'2016-5-4');
insert into employee_payroll(empname,salary,startDate) values('viju',78965,'2012-5-7');
insert into employee_payroll(empname,salary,startDate) values('Nagveni',7412,'2016-1-6');
select * from employee_payroll;
select salary from employee_payroll where empname='jaya';
select * from employee_payroll where startDate between cast('2015-01-05' as date) and date(now());
alter table employee_payroll add column gender varchar(1) after empname;
update employee_payroll set gender='F' where id>=1;
select * from employee_payroll;
insert into employee_payroll(empname,gender,salary,startDate) values('kavya','F',1000000,'2008-7-10');
insert into employee_payroll(empname,gender,salary,startDate) values('shree','F',8500,'2018-6-21');
insert into employee_payroll(empname,gender,salary,startDate) values('shilpa','F',78512,'2019-7-27');
select sum(salary) from employee_payroll where gender='F' group by gender;
select avg(salary) from employee_payroll where gender='F' group by gender;
select min(salary) from employee_payroll where gender='F' group by gender;
select max(salary) from employee_payroll where gender='M' group by gender;
select count(salary) from employee_payroll where gender='F' group by gender;
alter table employee_payroll add column empphone long;
alter table employee_payroll add column address varchar(50) default 'india';
alter table employee_payroll add column department varchar(20) not null;
desc employee_payroll;
alter table employee_payroll add column basicpay double;
alter table employee_payroll add column deductions double;
alter table employee_payroll add column taxablepay double;
alter table employee_payroll add column incomtax double;
alter table employee_payroll add column netpay double;
desc employee_payroll;
insert into employee_payroll(empname,gender,salary,startDate,empphone,address,department,basicpay,deductions,taxablepay,incomtax,netpay)
values('sujata','F',50000,'2020-05-06',8878786567,'Azam Nagar','Coder',7422,6500,8632,9521,95200);
insert into employee_payroll(empname,gender,salary,startDate,empphone,address,department,basicpay,deductions,taxablepay,incomtax,netpay)
values('Naina','F',7400000,'2019-01-21',9988997898,'Vidya Nagar','IT Department',6412,1500,3632,5521,15200);
select * from employee_payroll;
update employee_payroll set department='sales and marketing ' where id>1;
update employee_payroll set department='computer' where id>12 and id <16;
update employee_payroll set department='mechanical ' where id=16;
desc EmployeeDepartment;
insert into EmployeeDepartment(deptid) values(102);
insert into EmployeeDepartment(deptid) values(103);
select * from EmployeeDepartment;
delete from EmployeeDepartment where empid=1;
desc employee_payroll;
